version: '3.8'

services:
  frontend:
    image: node:18-alpine
    working_dir: /app
    volumes:
      - ./snadnee-assignment-fe:/app
      - /app/node_modules
    command: sh -c "npm ci && npm run serve"
    ports:
      - "8080:8080"
    networks:
      - app-network

  php_api:
    build:
      context: ./docker-conf/php-fpm
      dockerfile: Dockerfile
    working_dir: /var/www
    command: sh -c "php artisan migrate:fresh && php artisan db:seed && php-fpm"
    volumes:
      - ./snadnee-assignment-api:/var/www
    networks:
      - app-network
    depends_on:
      - db
      - composer

  composer:
    image: composer:latest
    networks:
      - app-network
    ports:
      - "9002:9000"
    volumes:
      - "./snadnee-assignment-api:/snadnee-assignment-api"
    working_dir: /snadnee-assignment-api
    command: install

  db:
    image: mysql:8.4.2
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: snadnee_assignment
      MYSQL_USER: snadnee_assignment
      MYSQL_PASSWORD: snadnee_assignment
    volumes:
      - ./mysql_data:/var/lib/mysql
    networks:
      - app-network
    ports:
      - "3306:3306"

  adminer:
    image: adminer
    container_name: adminer
    ports:
      - "8081:8080"
    networks:
      - app-network

  nginx_api:
    image: nginx:1.27.2-alpine
    volumes:
      - ./docker-conf/api-conf.conf:/etc/nginx/conf.d/default.conf
      - ./snadnee-assignment-api:/var/www
    ports:
      - "8082:80"
    depends_on:
      - php_api
    networks:
      - app-network

networks:
  app-network:
    driver: bridge